language: node_js
node_js:
  - "node"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
 
cache:
  directories:
     - ./node_modules

before_install:
  - npm i -g npm
install:
  - npm install -g firebase-tools
  - npm install
  - npm run build-live
after_success:
  - sudo firebase deploy --token $FIREBASE_TOKEN