language: node_js
node_js:
  - "node"
dist: trusty
sudo: required
before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
script:
- ng build --prod
deploy:
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  on:
    branch: job
