language: node_js
node_js:
- node
script:
- echo "Deploying!"
before_install:
- npm i -g npm
install:
  - npm install -g firebase-tools
  - npm install
  - npm run build
deploy:
  - sudo firebase deploy --token $FIREBASE_TOKEN
    on:
      branch:
      - job