language: node_js
node_js:
  - "node"
before_install:
  - npm i -g npm
install:
  - npm install -g firebase-tools
  - npm install
  - npm run build
after_success:
  - sudo firebase deploy --token $FIREBASE_TOKEN
  on:
    branch: job