language: node_js
node_js:
  - "node"
dist: trusty
sudo: required
before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
script:
- ng build --prod
after_success:
  - sudo firebase deploy --token $FIREBASE_TOKEN
