language: node_js
node_js:
  - "node"
cache: npm
dist: trusty
sudo: required
before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
script:
  - ng build --prod
deploy:
  provider: script
  script: bash deploy.sh